In [32]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [59]:
test = pd.read_csv("C:/Users/adith/Desktop/Datasets/Linear_test.csv")
test = (test - np.min(test)) / (np.max(test) - np.min(test)) 

train = pd.read_csv("C:/Users/adith/Desktop/Datasets/Linear_train.csv")
train = (train - np.min(train)) / (np.max(train) - np.min(train)) 
train.head()

,Unnamed: 0,A,B,C,D,E,F,G,H,I,...,L,M,N,O,P,Q,R,S,T,label
0,0.00000,0.405189,0.564946,0.581980,0.824021,0.694666,0.322253,0.761031,0.831233,0.378574,...,0.541070,0.800611,0.249985,0.613485,0.156706,0.872207,0.455593,0.776928,0.790221,0.466424
1,0.00002,0.332709,0.559042,0.623018,0.138323,0.562578,0.320408,0.629557,0.085946,0.833826,...,0.994529,0.486712,0.660244,0.909518,0.426283,0.955541,0.875766,0.622599,0.175711,0.630692
2,0.00004,0.230410,0.305883,0.143164,0.410290,0.044787,0.519500,0.498465,0.672524,0.162366,...,0.232111,0.430032,0.778496,0.752728,0.693254,0.141877,0.440868,0.642861,0.158109,0.528271
3,0.00006,0.114577,0.612737,0.210172,0.521590,0.152313,0.878746,0.738595,0.037246,0.340948,...,0.431072,0.375587,0.978869,0.852582,0.807867,0.721632,0.664658,0.895053,0.834593,0.824592
4,0.00008,0.152198,0.852272,0.172532,0.485968,0.359383,0.569211,0.940650,0.817915,0.099416,...,0.258436,0.609928,0.028567,0.421183,0.419146,0.891722,0.004595,0.188286,0.138303,0.310481

In [60]:
X = train.values[:, :-1]
Y = train.values[:, -1].reshape(train.values.shape[0], 1)

X_test = test.values[:, :-1]
Y_test = test.values[:, -1].reshape(test.values.shape[0], 1)

print(X.shape)
print(Y.shape)
print(X_test.shape)
print(Y_test.shape)

(50000, 21)
(50000, 1)
(10000, 21)
(10000, 1)

In [62]:
def model(X, Y, learning_rate, iteration):
    m = Y.size
    theta = np.zeros((21,1))
    cost_list = []
    
    for i in range(iteration):
        y_pred = np.dot(X, theta)
        cost = (1/(2*m))*np.sum(np.square(y_pred - Y))
        
        d_theta = (1/m)*np.dot(X.T, y_pred - Y)
        theta = theta - learning_rate*d_theta
        
        cost_list.append(cost)
        
        if(i%(iteration/10) == 0):
            print('Cost is:',cost)
            
    return theta, cost_list

In [63]:
iteration = 1000
learning_rate = 0.3
theta, cost_list = model(X, Y, learning_rate = learning_rate, iteration = iteration)

Cost is: 0.13368343512225278
Cost is: 0.00019538079957751638
Cost is: 0.00013529880176499774
Cost is: 0.00013481849359259674
Cost is: 0.00013481445680872778
Cost is: 0.00013481442137932247
Cost is: 0.0001348144210573663
Cost is: 0.00013481442105436244
Cost is: 0.00013481442105433387
Cost is: 0.0001348144210543336

In [64]:
y_pred = np.dot(X_test, theta)
error = (1/X_test.shape[0])*np.sum(np.abs(y_pred - Y_test))
rmse = np.sqrt(((y_pred-Y_test)**2).mean())
print(rmse)
print("Test error is:", error*100,"%")
print("Test accuracy is:", (1-error)*100, "%")

0.01860370182852447
Test error is: 1.49232391810033 %
Test accuracy is: 98.50767608189967 %